// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Mocking supabase to avoid dependencies while not in use
// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });

// Mock implementation
export const supabase = {
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
  },
  from: () => ({
    select: () => ({
      order: () => ({ data: [], error: null }),
      data: [],
      error: null
    }),
  }),
  functions: {
    invoke: async () => ({ data: null, error: null }),
  }
} as any;